// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2M2ChdsX1KruEp8MDkIKGcIFCCf55hhw',
    appId: '1:316319701183:web:25a3b89c50ae8209410e0a',
    messagingSenderId: '316319701183',
    projectId: 'email-notification-8b5f3',
    authDomain: 'email-notification-8b5f3.firebaseapp.com',
    storageBucket: 'email-notification-8b5f3.appspot.com',
    measurementId: 'G-MMLS8YN6SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCW9Fj7RXWbmU7GYxFcgekeyLin1_VQE8',
    appId: '1:316319701183:android:73c47e95a0ae0afa410e0a',
    messagingSenderId: '316319701183',
    projectId: 'email-notification-8b5f3',
    storageBucket: 'email-notification-8b5f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRfgBw78Wh6-ZcnMkASIBkaAaCHfuF1GM',
    appId: '1:316319701183:ios:73e81970a9867637410e0a',
    messagingSenderId: '316319701183',
    projectId: 'email-notification-8b5f3',
    storageBucket: 'email-notification-8b5f3.appspot.com',
    iosBundleId: 'com.example.emailAlertGeneration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRfgBw78Wh6-ZcnMkASIBkaAaCHfuF1GM',
    appId: '1:316319701183:ios:0cb05c630a99c882410e0a',
    messagingSenderId: '316319701183',
    projectId: 'email-notification-8b5f3',
    storageBucket: 'email-notification-8b5f3.appspot.com',
    iosBundleId: 'com.example.emailAlertGeneration.RunnerTests',
  );
}
